// <auto-generated />
namespace SistemaAcademia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class adionarepository : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adionarepository));
        
        string IMigrationMetadata.Id
        {
            get { return "202108132232311_adiona repository"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
